# Generated by Django 5.1 on 2024-10-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_date_of_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_path',
            field=models.ImageField(blank=True, null=True, upload_to='./profile_pics'),
        ),
    ]
