# Generated by Django 5.1 on 2024-10-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leave_reason_alter_user_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateField(),
        ),
    ]
