# Generated by Django 5.1 on 2024-10-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
