# Generated by Django 4.2.7 on 2024-11-25 12:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
    ]
