# Generated by Django 4.2.7 on 2024-11-25 13:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_log_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
